// omnishell's command line: the entry point every consumer of the terminal
// reaches its checkers through.
//
//   omnishell check markup|handlers|machines <appDir> | --self-test
//   omnishell read markup <appDir> | --self-test
//   omnishell mode <appDir> [--local]
//
// What a check needs from deno — a lockfile policy, a type-check policy, a
// module resolution, a config, a permission grant, the path to a program —
// is the tool's business and not its caller's, so all of it lives behind this
// entry: the launcher beside this file states the deno half, and each leaf
// below states what it runs on. A caller writes a command.
//
// The launcher grants the union of what the leaves need, because deno takes
// its permissions at startup and a leaf is chosen after that. Each leaf then
// gives back what it does not use, before the checker it names is called:
// `check markup` reads app source it never evaluates, so it runs on the app
// directory and nothing else, while `check handlers` evaluates that source in
// the vendored SES compartment and needs the interpreter to reach it. A
// self-test reads its fixtures from test/ whichever leaf it is.
//
// Every leaf's output is its checker's own — the findings JSON on stdout, the
// count on stderr, the exit code the severity band decides. Nothing here
// prints, so a caller parsing stdout parses what the checker said.

import { fileURLToPath, pathToFileURL } from "node:url";

const root = new URL("../", import.meta.url);

// A directory of the tool's own tree, spelled the way the filesystem does —
// which is what a permission descriptor is matched against, and what a URL
// pathname, percent-encoded and drive-prefixed, is not.
function toolDir(name: string): string {
  return fileURLToPath(new URL(name, root));
}

const usage = [
  "usage: omnishell check markup|handlers|machines <appDir> | --self-test",
  "       omnishell read markup <appDir> | --self-test",
  "       omnishell mode <appDir> [--local]",
].join("\n");

function refuse(message: string): never {
  console.error(message);
  console.error(usage);
  Deno.exit(1);
}

// Hands back what this leaf does not use, of the two directories of the tool's
// own tree the launcher grants: the interpreter a check evaluates app source
// against, and the fixtures a self-test answers on. The app directory is the
// caller's and stays: a revoke hands back every grant enclosing the path it
// names, and a leaf is run from an app directory, which encloses neither.
async function narrow(opts: { env: boolean; interpreter: boolean; fixtures: boolean }): Promise<void> {
  if (!opts.env) await Deno.permissions.revoke({ name: "env" });
  if (!opts.interpreter) await Deno.permissions.revoke({ name: "read", path: toolDir("interpreter") });
  if (!opts.fixtures) await Deno.permissions.revoke({ name: "read", path: toolDir("test") });
}

// A URL's own spelling of a directory, as the arithmetic below needs it:
// decoded, and without the trailing slash that would leave an empty segment.
// Separators stay URL separators, so an app names this runtime the same way on
// every platform and the stanza a checkout generates is one file.
function dirPath(url: URL): string {
  return decodeURIComponent(url.pathname).replace(/\/+$/, "");
}

// A directory named from another one, which is how an app names this runtime:
// the commands run in the app's directory, so the path is stated from there.
function pathFrom(base: string, target: string): string {
  const here = base.split("/");
  const there = target.split("/");
  let shared = 0;
  while (shared < here.length && shared < there.length && here[shared] === there[shared]) shared++;
  return [...here.slice(shared).map(() => ".."), ...there.slice(shared)].join("/");
}

// The stanza that tells an app's program which terminal its commands name: this
// tree, stated as a path from the app, or the empty string for the `omnishell`
// on PATH. It unifies into the app's own package, so it carries that package's
// name, read from the program it sits beside.
async function mode(appDir: string, local: boolean): Promise<void> {
  const cwd = `${pathToFileURL(Deno.cwd()).href}/`;
  const dir = new URL(`${appDir.replace(/\/*$/, "")}/`, cwd);
  const program = await Deno.readTextFile(new URL("program.cue", dir));
  const declared = program.match(/^package\s+(\w+)\s*$/m);
  if (declared === null) throw new Error(`${appDir}/program.cue declares no package`);
  const runtime = local ? pathFrom(dirPath(dir), dirPath(new URL("./", import.meta.url))) : "";
  console.log(
    [
      "// generated by omnishell from the layout this app is built in — do not edit",
      "",
      `package ${declared[1]}`,
      "",
      `terminal: surface: runtime: ${JSON.stringify(runtime)}`,
    ].join("\n"),
  );
}

const [verb, ...rest] = Deno.args;

if (verb === "mode") {
  const [appDir, ...flags] = rest;
  if (appDir === undefined) refuse("mode: no app directory");
  if (flags.length > 1 || (flags.length === 1 && flags[0] !== "--local")) {
    refuse(`mode: ${flags.join(" ")}`);
  }
  await narrow({ env: false, interpreter: false, fixtures: false });
  await mode(appDir, flags[0] === "--local");
} else if (verb === "check" || verb === "read") {
  const [noun, ...args] = rest;
  if (noun === undefined) refuse(`${verb}: no leaf`);
  const leaf = `${verb} ${noun}`;
  const selfTest = args[0] === "--self-test";
  if (args.length !== 1) refuse(`${leaf}: one <appDir> or --self-test`);
  switch (leaf) {
    case "check markup": {
      const { run } = await import("../check-markup.ts");
      await narrow({ env: false, interpreter: false, fixtures: selfTest });
      await run(args);
      break;
    }
    case "check handlers": {
      const { run } = await import("../check-handlers.ts");
      await narrow({ env: true, interpreter: true, fixtures: selfTest });
      await run(args);
      break;
    }
    case "check machines": {
      const { run } = await import("../check-machines.ts");
      await narrow({ env: true, interpreter: true, fixtures: selfTest });
      await run(args);
      break;
    }
    case "read markup": {
      const { run } = await import("../read-markup.ts");
      await narrow({ env: false, interpreter: false, fixtures: selfTest });
      await run(args);
      break;
    }
    default:
      refuse(`no such check: ${leaf}`);
  }
} else {
  refuse(verb === undefined ? "omnishell: no subcommand" : `no such subcommand: ${verb}`);
}
